version: '3.8'

services:
  messagebus:
    image: 'rabbitmq:3.11-management-alpine'
    container_name: messagebus
    hostname: messagebus
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - demos

networks:
  demos:
    driver: bridge